/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chefsuggest

import chefsuggest.core.Meal
import chefsuggest.core.Recipe
import chefsuggest.core.XmlMealHandler
import javax.xml.parsers.SAXParserFactory

class App {
}

fun main() {
    val saxParser = SAXParserFactory.newInstance().newSAXParser()
    val mealHandler = XmlMealHandler()
    saxParser.parse("app/src/test/kotlin/chefsuggest/resources/TestOne.xml", mealHandler)
    val temp = Meal(
        name = "Macaroni and Cheese",
        tags = mutableListOf("Meal", "Side", "Dairy"),
        Recipe(
            url = "https://recipe.com",
            ingredients = mutableListOf("Macaroni Noodles", "Cheese", "Milk"),
            steps = mutableListOf("Step One", "Step Two", "Step Three")
        )
    )
    val areEqual = mealHandler.getMeal() == temp
    println("Meal Equal: $areEqual")
}
