/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chefsuggest

import chefsuggest.core.XmlMealHandler
import javax.xml.parsers.SAXParserFactory

class App {
}

fun main() {
    val saxParser = SAXParserFactory.newInstance().newSAXParser()
    val mealHandler = XmlMealHandler()
    saxParser.parse("ChefSuggestData/MacNCheese.xml", mealHandler)
    println(mealHandler.getMeal())
//    val window = ChefSuggestWindow.getInstance();
//    window.isVisible = true;
}
